services:
  db:
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: authapi
      POSTGRES_PASSWORD: authapi
      POSTGRES_DB: authapi
    ports:
      - "5433:5432"
    networks:
      - gateway_network

  userapi:
    build:
      context: ./backend/UserAPI
      dockerfile: ./src/Infrastructure/Docker/Dockerfile
    ports:
      - "3001:8080"
    depends_on:
      - db
    networks:
      - gateway_network

  machineapi:
     build:
       context: ./backend/MachineAPI
       dockerfile: ./src/Infrastructure/Docker/Dockerfile
     ports:
       - "3002:8080"
     depends_on:
       - db
     networks:
       - gateway_network

  toolapi:
     build:
       context: ./backend/ToolAPI
       dockerfile: ./Dockerfile
     ports:
       - "3003:8080"
     depends_on:
       - db
     networks:
       - gateway_network

  apigateway:
    build:
      context: ./backend/ApiGateway
      dockerfile: ./Dockerfile
    ports:
      - "3004:8080"
    depends_on:
      - userapi
      - machineapi
    networks:
     - gateway_network

  maintenance:
    build:
      context: ./backend/Maintenance
      dockerfile: ./Dockerfile
    ports:
      - "3005:8080"
    depends_on:
      -  db
    networks:
     - gateway_network

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   networks:
  #    - gateway_network

  # mobile:
  #   container_name: mobile-academy
  #   build:
  #     context: ./mobile
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8081:8081"
  #   networks:
  #    - gateway_network

networks:
  gateway_network:
    driver: bridge