services:
  db:
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: authapi
      POSTGRES_PASSWORD: authapi
      POSTGRES_DB: authapi
    ports:
      - "5432:5432"
    networks:
      - gateway_network

  userapi:
    build:
      context: .
      dockerfile: ./UserAPI/src/Infrastructure/Docker/Dockerfile
    ports:
      - "3000:8080"
    depends_on:
      - db
    networks:
      - gateway_network

  machineapi:
     build:
       context: .
       dockerfile: ./MachineAPI/src/Infrastructure/Docker/Dockerfile
     ports:
       - "3001:8080"
     depends_on:
       - db
     networks:
       - gateway_network

  apigateway:
    build:
      context: .
      dockerfile: ./ApiGateway/Dockerfile
    ports:
      - "3002:8080"
    depends_on:
      - userapi
      - machineapi
    networks:
     - gateway_network

networks:
  gateway_network:
    driver: bridge
